# Generated by Django 5.2 on 2025-05-19 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Categoría')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de Noticia',
                'verbose_name_plural': 'Categorías de Noticia',
                'db_table': 'categorias_noticia',
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Entrevista')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entrevistas/', verbose_name='Imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo de la imagen')),
                ('duracion', models.DurationField(verbose_name='Duración')),
                ('vistas', models.IntegerField(default=0, verbose_name='Vistas')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'db_table': 'entrevistas',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Género')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id_suscriptor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Suscriptor')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fechas_suscripcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de suscripción')),
                ('estado', models.CharField(default='activo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Suscripción al Newsletter',
                'verbose_name_plural': 'Suscripciones al Newsletter',
                'db_table': 'newsletter',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Contenido')),
                ('tipo_contenido', models.CharField(max_length=50, verbose_name='Tipo de Contenido')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('año_estreno', models.IntegerField(verbose_name='Año de estreno')),
                ('duracion', models.DurationField(verbose_name='Duración')),
                ('director', models.CharField(max_length=200, verbose_name='Director')),
                ('guionistas', models.TextField(verbose_name='Guionistas')),
                ('clasificacion', models.CharField(max_length=10, verbose_name='Clasificación')),
                ('imagen_poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Póster')),
                ('alt_imagen_poster', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo del póster')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='fondos/', verbose_name='Imagen de fondo')),
                ('alt_imagen_fondo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo de la imagen de fondo')),
                ('puntuacion', models.FloatField(verbose_name='Puntuación')),
                ('es_exclusivo', models.BooleanField(default=False, verbose_name='¿Es exclusivo?')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'contenidos',
                'indexes': [models.Index(fields=['tipo_contenido'], name='contenidos_tipo_co_bdb3fb_idx'), models.Index(fields=['titulo'], name='contenidos_titulo_cadfcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Comentario')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del comentario')),
                ('likes', models.IntegerField(default=0, verbose_name='Me gusta')),
                ('dislikes', models.IntegerField(default=0, verbose_name='No me gusta')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='base.comentario', verbose_name='Comentario padre')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('id_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='base.contenido', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Imagen')),
                ('url_imagen', models.ImageField(blank=True, null=True, upload_to='galeria/', verbose_name='Imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo de la imagen')),
                ('id_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='base.contenido', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galerías',
                'db_table': 'galeria',
            },
        ),
        migrations.CreateModel(
            name='ListaPersonalizada',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Lista')),
                ('nombre_lista', models.CharField(max_length=100, verbose_name='Nombre de la lista')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista Personalizada',
                'verbose_name_plural': 'Listas Personalizadas',
                'db_table': 'listas_personalizadas',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Noticia')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen principal')),
                ('alt_imagen_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo de la imagen principal')),
                ('vistas', models.IntegerField(default=0, verbose_name='Vistas')),
                ('tiempo_lectura', models.DurationField(verbose_name='Tiempo de lectura')),
                ('es_exclusiva', models.BooleanField(default=False, verbose_name='¿Es exclusiva?')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'noticias',
                'indexes': [models.Index(fields=['titulo'], name='noticias_titulo_5622c4_idx'), models.Index(fields=['fecha_publicacion'], name='noticias_fecha_p_a63e80_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Notificación')),
                ('tipo_notificacion', models.CharField(max_length=50, verbose_name='Tipo de notificación')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envío')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Perfil')),
                ('nombre_perfil', models.CharField(max_length=100, verbose_name='Nombre del Perfil')),
                ('imagen_avatar', models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Avatar')),
                ('alt_imagen_avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo del avatar')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='PlataformaStreaming',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Plataforma')),
                ('nombre_plataforma', models.CharField(max_length=100, verbose_name='Nombre de la Plataforma')),
                ('imagen_logo_plataforma', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la Plataforma')),
                ('alt_imagen_logo_plataforma', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo del logo')),
                ('tipo_acceso', models.CharField(max_length=50, verbose_name='Tipo de acceso')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('id_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plataformas', to='base.contenido', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Plataforma de Streaming',
                'verbose_name_plural': 'Plataformas de Streaming',
                'db_table': 'plataformas_streaming',
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id_reparto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Reparto')),
                ('id_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparto', to='base.contenido', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Reparto',
                'verbose_name_plural': 'Repartos',
                'db_table': 'reparto',
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Actor')),
                ('nombre_actor', models.CharField(max_length=100, verbose_name='Nombre del Actor')),
                ('personaje', models.CharField(max_length=100, verbose_name='Personaje')),
                ('imagen_actor', models.ImageField(blank=True, null=True, upload_to='actores/', verbose_name='Imagen del Actor')),
                ('id_reparto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actores', to='base.reparto', verbose_name='Reparto')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Suscripción')),
                ('tipo_suscripcion', models.CharField(max_length=50, verbose_name='Tipo de Suscripción')),
                ('es_premium', models.BooleanField(default=False, verbose_name='¿Es Premium?')),
                ('fecha_fin_suscripcion', models.DateField(verbose_name='Fecha de fin de suscripción')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción de Usuario',
                'verbose_name_plural': 'Suscripciones de Usuario',
                'db_table': 'suscripciones_usuario',
            },
        ),
        migrations.CreateModel(
            name='ContenidoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contenido', verbose_name='Contenido')),
                ('id_genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.genero', verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Género de Contenido',
                'verbose_name_plural': 'Géneros de Contenido',
                'db_table': 'contenidos_generos',
                'unique_together': {('id_contenido', 'id_genero')},
            },
        ),
        migrations.CreateModel(
            name='ListaContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contenido', verbose_name='Contenido')),
                ('id_lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.listapersonalizada', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Contenido de Lista Personalizada',
                'verbose_name_plural': 'Contenidos de Listas Personalizadas',
                'db_table': 'lista_personalizadas_contenidos',
                'unique_together': {('id_lista', 'id_contenido')},
            },
        ),
        migrations.CreateModel(
            name='NoticiaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorianoticia', verbose_name='Categoría')),
                ('id_noticias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.noticia', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Categoría de Noticia',
                'verbose_name_plural': 'Categorías de Noticia',
                'db_table': 'noticias_categorias',
                'unique_together': {('id_noticias', 'id_categoria')},
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Valoración')),
                ('puntuacion', models.FloatField(verbose_name='Puntuación')),
                ('texto_valoracion', models.TextField(blank=True, verbose_name='Texto de la valoración')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='base.contenido', verbose_name='Contenido')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'db_table': 'valoraciones',
                'unique_together': {('id_usuario', 'id_contenido')},
            },
        ),
    ]
