# Generated by Django 5.2 on 2025-05-14 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categorias_noticia',
                'db_table': 'categorias_noticia',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contenido', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.DurationField()),
                ('director', models.TextField()),
                ('guionistas', models.TextField()),
                ('clasificacion', models.CharField(max_length=10)),
                ('imagen_poster', models.ImageField(upload_to='posters/')),
                ('imagen_fondo', models.ImageField(upload_to='fondos/')),
                ('puntuacion_imdb', models.FloatField()),
                ('es_exclusivo', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contenidos',
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='entrevistas/')),
                ('duracion', models.DurationField()),
                ('descripcion', models.TextField()),
                ('vistas', models.IntegerField(default=0)),
                ('tiempo_lectura', models.DurationField()),
                ('es_exclusiva', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'entrevistas',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'generos',
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='base.comentario')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='base.contenido')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('descripcion_imagen', models.TextField(blank=True)),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='base.contenido')),
            ],
            options={
                'db_table': 'galeria',
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='generos',
            field=models.ManyToManyField(related_name='contenidos', to='base.genero'),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id_suscriptor', models.AutoField(primary_key=True, serialize=False)),
                ('fechas_suscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'newsletter',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('imagen_principal', models.ImageField(upload_to='noticias/')),
                ('vistas', models.IntegerField(default=0)),
                ('tiempo_lectura', models.DurationField()),
                ('es_exclusiva', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorias', models.ManyToManyField(related_name='noticias', to='base.categorianoticia')),
            ],
            options={
                'db_table': 'noticias',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='avatares/')),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='ListaPersonalizada',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lista', models.CharField(max_length=100)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenidos', models.ManyToManyField(related_name='listas', to='base.contenido')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='base.perfil')),
            ],
            options={
                'db_table': 'lista_personalizadas',
            },
        ),
        migrations.CreateModel(
            name='PlataformaStreaming',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plataforma', models.CharField(max_length=100)),
                ('url_contenido', models.URLField()),
                ('fecha_lanzamiento', models.DateField()),
                ('es_exclusivo', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas', to='base.contenido')),
            ],
            options={
                'db_table': 'plataformas_streaming',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('puntuacion', models.FloatField()),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='base.contenido')),
            ],
            options={
                'db_table': 'recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id_reparto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actor', models.CharField(max_length=100)),
                ('personaje', models.CharField(max_length=100)),
                ('imagen_actor', models.ImageField(blank=True, upload_to='actores/')),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparto', to='base.contenido')),
            ],
            options={
                'db_table': 'reparto',
            },
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_suscripcion', models.CharField(max_length=50)),
                ('es_premium', models.BooleanField(default=False)),
                ('fecha_fin_suscripcion', models.DateField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suscripciones_usuario',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.FloatField()),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='base.contenido')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'valoraciones',
            },
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['tipo_contenido'], name='contenidos_tipo_co_bdb3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['titulo'], name='contenidos_titulo_cadfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['fecha_estreno'], name='contenidos_fecha_e_6aaa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['titulo'], name='noticias_titulo_5622c4_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['fecha_publicacion'], name='noticias_fecha_p_a63e80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('id_usuario', 'id_contenido')},
        ),
    ]
