# Generated by Django 5.2 on 2025-05-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contenidogenero',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='listacontenido',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='noticiacategoria',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together=set(),
        ),
    ]
