# Generated by Django 5.2 on 2025-05-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contenidogenero',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='listacontenido',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='noticiacategoria',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Usuario'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
