# Generated by Django 5.2 on 2025-05-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiacategoria',
            name='creador',
        ),
    ]
