# Generated by Django 5.2 on 2025-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_contenidogenero_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiacategoria',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='noticiacategoria',
            name='id_noticias',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Cine', 'Cine'), ('Series', 'Series'), ('Entrevistas', 'Entrevistas'), ('Reseñas', 'Reseñas'), ('Premios', 'Premios'), ('Trailers', 'Trailers'), ('Estrenos', 'Estrenos')], max_length=100, verbose_name='Categoría'),
        ),
        migrations.DeleteModel(
            name='CategoriaNoticia',
        ),
        migrations.DeleteModel(
            name='NoticiaCategoria',
        ),
    ]
