# Generated by Django 5.2 on 2025-05-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_noticiacategoria_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='duracion',
            field=models.IntegerField(verbose_name='Duración'),
        ),
    ]
