# Generated by Django 5.2 on 2025-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_noticiacategoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='tiempo_lectura',
            field=models.IntegerField(verbose_name='Tiempo de lectura'),
        ),
    ]
