# Generated by Django 5.2 on 2025-06-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_noticia_tiempo_lectura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrevista',
        ),
    ]
