# Generated by Django 5.2 on 2025-06-11 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_entrevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listapersonalizada',
            name='id_usuario',
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Lista')),
                ('id_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='base.contenido', verbose_name='Contenido')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'db_table': 'listas',
            },
        ),
        migrations.DeleteModel(
            name='ListaContenido',
        ),
        migrations.DeleteModel(
            name='ListaPersonalizada',
        ),
    ]
