"""
Django settings for proyecto_sonaura project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@tr_u&8*z5d(fy$$75leg7xuujo80_87jw+l#p$*6c_!v!!60c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'base',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_sonaura.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_sonaura.wsgi.application'


# Nombre usuario adminSonaura
# Contraseña usuario adminSonaura_TFG2025
# 'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'railway',  # nombre de la base de datos
#         'USER': 'root',     # usuario
#         'PASSWORD': 'bnLszbhgNdaRKguyqtBYcrbdDWMdmFRn',  # contraseña
#         'HOST': 'ballast.proxy.rlwy.net',  # solo el host, sin mysql:// ni usuario ni contraseña
#         'PORT': '32204',    # el puerto correcto según Railway
#     }
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'railway',  # nombre de la base de datos
        'USER': 'root',     # usuario
        'PASSWORD': 'bnLszbhgNdaRKguyqtBYcrbdDWMdmFRn',  # contraseña
        'HOST': 'ballast.proxy.rlwy.net',  # solo el host, sin mysql:// ni usuario ni contraseña
        'PORT': '32204',    # el puerto correcto según Railway
    },
    'localhost': {
        'ENGINE': 'django.db.backends.mysql',# Indica que usarás MySQL
        'NAME': 'sonaura', # Reemplaza con el nombre de tu base de datos
        'USER': 'sonaura', # Reemplaza con tu usuario de MySQL
        'PASSWORD': 'sonaura', # Reemplaza con la contraseña de tu usuario
        'HOST': 'localhost', # Dirección del servidor MySQL (usualmente localhost)
        'PORT': '3306', # Puerto de conexión (por defecto 3306)
    }
}


# Password validation 
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS=[
    BASE_DIR / "static", #directorio ocal donde colocoras tus archvios estaticos
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

#imagenes
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Tiempo de vida del token de acceso
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Tiempo de vida del token de refresco
    'ROTATE_REFRESH_TOKENS': True,  # Renovar automáticamente el token de refresco
    'BLACKLIST_AFTER_ROTATION': True,  # Evitar reutilización de tokens viejos
    'ALGORITHM': 'HS256',  # Algoritmo de encriptación
    'SIGNING_KEY': SECRET_KEY,  # Usa la clave secreta del proyecto DJANGO
}
