-- 2. Películas taquilleras
INSERT INTO contenidos (id_contenido, titulo, pelicula_serie, eslogan, sinopsis, año_estreno, duracion, director, guionistas, clasificacion, imagen_poster, alt_imagen_poster, imagen_fondo, alt_imagen_fondo, puntuacion, es_exclusivo, fecha_edicion, fecha_creacion, creador_id)
VALUES
(1, 'Avatar', 'pelicula', 'Entra en Pandora', 'Jake Sully, un ex-marine parapléjico, es enviado al exuberante planeta Pandora para infiltrarse entre los Na’vi, una raza indígena. Usando un avatar alienígena, descubre un mundo de maravillas y conflictos. Dividido entre su misión y su conexión con los Na’vi, Jake debe elegir un bando en una épica batalla por la supervivencia y el equilibrio de la naturaleza.', 2009, 162, 'James Cameron', 'James Cameron', 'PG-13', 'posters/Avatar.jpg', 'Avatar', NULL, NULL, 7.8, 0, NOW(), NOW(), 1),
(2, 'Avengers: Endgame', 'pelicula', 'El final del juego', 'Tras una devastadora derrota, los Vengadores supervivientes se unen para revertir las acciones de Thanos, quien aniquiló a la mitad de la humanidad. Con el tiempo como su mayor enemigo, emprenden una misión épica llena de sacrificios y decisiones imposibles, donde el destino del universo pende de un hilo en esta culminante batalla de superhéroes.', 2019, 181, 'Anthony y Joe Russo', 'Christopher Markus, Stephen McFeely', 'PG-13', 'posters/Avengers Endgame.jpg', 'Avengers: Endgame', NULL, NULL, 8.4, 0, NOW(), NOW(), 1),
(3, 'Titanic', 'pelicula', 'Nada en la Tierra podría separarlos', 'En 1912, Rose, una joven de clase alta, y Jack, un artista bohemio, se enamoran a bordo del lujoso Titanic. Su apasionado romance desafía las barreras sociales, pero el destino del barco, en ruta hacia un trágico iceberg, pone a prueba su amor y su lucha por la supervivencia en una de las mayores catástrofes marítimas de la historia.', 1997, 194, 'James Cameron', 'James Cameron', 'PG-13', 'posters/Titanic.jpg', 'Titanic', NULL, NULL, 7.9, 0, NOW(), NOW(), 1),
(4, 'Star Wars: The Force Awakens', 'pelicula', 'Despierta la fuerza', 'Décadas después de la caída del Imperio, una nueva amenaza, la Primera Orden, emerge en la galaxia. Rey, una recolectora de chatarra, y Finn, un desertor de los stormtroopers, se unen a la Resistencia para enfrentar al malvado Kylo Ren. Con la ayuda de leyendas como Han Solo, su aventura destapa secretos que podrían cambiar el destino de la galaxia.', 2015, 138, 'J.J. Abrams', 'Lawrence Kasdan, J.J. Abrams', 'PG-13', 'posters/Star Wars The Force Awakens.webp', 'Star Wars: The Force Awakens', NULL, NULL, 7.8, 0, NOW(), NOW(), 1),
(5, 'Jurassic World', 'pelicula', 'El parque ha abierto', 'En Isla Nublar, un parque temático de dinosaurios de última generación atrae a millones. Pero cuando un nuevo híbrido genético, el Indominus Rex, escapa, el caos se desata. Owen, un entrenador de velociraptores, y Claire, la gerente del parque, lideran una desesperada misión para salvar a los visitantes y restaurar el orden en un mundo donde la naturaleza reclama su poder.', 2015, 124, 'Colin Trevorrow', 'Rick Jaffa, Amanda Silver', 'PG-13', 'posters/Jurassic World.jpg', 'Jurassic World', NULL, NULL, 7.0, 0, NOW(), NOW(), 1),
(6, 'The Lion King', 'pelicula', 'Siente el rugido', 'Simba, un joven león destinado a ser rey, enfrenta la traición y el exilio tras la muerte de su padre. Guiado por nuevos amigos y el espíritu de su pasado, emprende un viaje de autodescubrimiento para reclamar su lugar en la Roca del Rey. Esta vibrante reimaginación en acción real celebra el legado, el coraje y el ciclo de la vida.', 2019, 118, 'Jon Favreau', 'Jeff Nathanson', 'PG', 'posters/The Lion King.jpg', 'The Lion King', NULL, NULL, 6.8, 0, NOW(), NOW(), 1),
(7, 'The Avengers', 'pelicula', 'Reunidos', 'Cuando Loki amenaza la Tierra con una invasión alienígena, Nick Fury reúne a un grupo dispar de superhéroes: Iron Man, Capitán América, Thor, Hulk, Viuda Negra y Ojo de Halcón. Juntos, deben superar sus diferencias y unir fuerzas en una batalla épica para salvar al mundo de la destrucción, demostrando que el verdadero poder radica en el trabajo en equipo.', 2012, 143, 'Joss Whedon', 'Joss Whedon', 'PG-13', 'posters/The Avengers.jpg', 'The Avengers', NULL, NULL, 8.0, 0, NOW(), NOW(), 1),
(8, 'Furious 7', 'pelicula', 'Una última carrera', 'Dom Toretto y su equipo enfrentan una nueva amenaza: Deckard Shaw, un letal asesino que busca vengarse. Entre carreras de alta velocidad, acrobacias imposibles y lealtades puestas a prueba, la familia debe unirse para proteger a los suyos y detener a Shaw en una aventura global cargada de adrenalina, donde el pasado regresa con fuerza y el peligro acecha en cada curva.', 2015, 137, 'James Wan', 'Chris Morgan', 'PG-13', 'posters/Furious 7.jpg', 'Furious 7', NULL, NULL, 7.1, 0, NOW(), NOW(), 1),
(9, 'Frozen II', 'pelicula', 'El viaje continúa', 'Elsa, Anna, Kristoff, Olaf y Sven se aventuran más allá de Arendelle para descubrir el origen de los poderes de Elsa. Una misteriosa voz la llama hacia un bosque encantado, donde enfrentarán peligros y secretos del pasado. En esta mágica odisea, las hermanas aprenderán que el amor y la valentía son la clave para proteger su reino y su vínculo.', 2019, 103, 'Chris Buck, Jennifer Lee', 'Jennifer Lee', 'PG', 'posters/Frozen II.jpg', 'Frozen II', NULL, NULL, 6.8, 0, NOW(), NOW(), 1),
(10, 'Beauty and the Beast', 'pelicula', 'La belleza está en el interior', 'Bella, una joven soñadora, se sacrifica para salvar a su padre y queda atrapada en el castillo de una misteriosa Bestia. A medida que descubre la bondad oculta tras su apariencia, surge un amor que desafía encantamientos y prejuicios. Esta mágica adaptación en acción real explora la redención, el coraje y la fuerza de los lazos que trascienden las apariencias.', 2017, 129, 'Bill Condon', 'Stephen Chbosky, Evan Spiliotopoulos', 'PG', 'posters/Beauty and the Beast.jpg', 'Beauty and the Beast', NULL, NULL, 7.1, 0, NOW(), NOW(), 1),
(11, 'Dune: Parte 2', 'pelicula', 'Entra en el desierto', 'Paul Atreides abraza su destino entre los Fremen de Arrakis, mientras la galaxia se tambalea bajo conspiraciones y guerras por el control de la especia. Aliado con Chani, lidera una rebelión contra las fuerzas opresoras. Esta épica continuación combina intriga política, misticismo y batallas colosales en un desierto donde el poder y la profecía chocan con consecuencias universales.', 2024, 166, 'Denis Villeneuve', 'Denis Villeneuve, Jon Spaihts', 'PG-13', 'posters/DuneParte2.jpg', 'Dune: Parte 2', NULL, NULL, 9.8, 0, NOW(), NOW(), 1),
(12, 'Oppenheimer', 'pelicula', 'El hombre detrás de la bomba', 'J. Robert Oppenheimer, un brillante físico, lidera el Proyecto Manhattan para crear la primera bomba atómica durante la Segunda Guerra Mundial. Su genialidad choca con dilemas éticos y políticos mientras el arma redefine el destino de la humanidad. Este drama histórico explora el peso de la ambición, el sacrificio y las consecuencias de un descubrimiento que cambió el mundo para siempre.', 2023, 180, 'Christopher Nolan', 'Christopher Nolan', 'PG-13', 'posters/Oppenheimer.jpg', 'Oppenheimer', NULL, NULL, 9.6, 0, NOW(), NOW(), 1),
(13, 'Pobres Criaturas', 'pelicula', 'Una vida extraordinaria', 'Bella Baxter, resucitada por un excéntrico científico, despierta a un mundo de maravillas y excesos. Su insaciable curiosidad la lleva a un viaje de autodescubrimiento, desafiando normas sociales y explorando el amor, la libertad y la identidad. Esta fábula surrealista, cargada de humor negro y audacia visual, reimagina el poder de la voluntad humana en un mundo extraño y fascinante.', 2023, 141, 'Yorgos Lanthimos', 'Tony McNamara', 'R', 'posters/PoorThings.jpg', 'Pobres Criaturas', NULL, NULL, 9.4, 0, NOW(), NOW(), 1),
(14, 'Civil War', 'pelicula', 'El país dividido', 'En un Estados Unidos fracturado por una guerra civil moderna, un grupo de periodistas recorre un país devastado para documentar la verdad. Entre ciudades destruidas y facciones enfrentadas, enfrentan peligros mortales mientras intentan llegar a Washington D.C. Este thriller distópico explora la fragilidad de la democracia y el costo humano de un conflicto que divide a una nación.', 2024, 109, 'Alex Garland', 'Alex Garland', 'R', 'posters/CivilWar.jpg', 'Civil War', NULL, NULL, 9.2, 0, NOW(), NOW(), 1),
(15, 'Rivales', 'pelicula', 'Competencia sin límites', 'Tashi, una ex-promesa del tenis convertida en entrenadora, guía a su esposo hacia la grandeza en la cancha, pero su pasado se reaviva cuando enfrentan a un antiguo amigo y rival. En un torbellino de pasión, ambición y secretos, este triángulo amoroso en el mundo del tenis profesional desafía lealtades y desata emociones intensas en cada punto del juego.', 2024, 131, 'Luca Guadagnino', 'Justin Kuritzkes', 'R', 'posters/Rivales.jpg', 'Rivales', NULL, NULL, 9.0, 0, NOW(), NOW(), 1),
(16, 'El Planeta de los Simios: Nuevo Reino', 'pelicula', 'Un nuevo comienzo', 'Siglos después del reinado de César, una nueva generación de simios construye una civilización avanzada. Noa, un joven líder, se enfrenta a un tirano que amenaza el futuro de su especie. Aliado con una humana misteriosa, emprende una aventura que revela secretos del pasado y redefine la convivencia entre simios y humanos en un mundo al borde del cambio.', 2024, 145, 'Wes Ball', 'Josh Friedman', 'PG-13', 'posters/PlanetaDeLosSimios.jpeg', 'El Planeta de los Simios: Nuevo Reino', NULL, NULL, 8.8, 0, NOW(), NOW(), 1),
(17, 'Furiosa: De la Saga Mad Max', 'pelicula', 'El origen de Furiosa', 'En un páramo postapocalíptico, la joven Furiosa es arrancada de su hogar y cae en manos de un señor de la guerra. Su lucha por sobrevivir y regresar a casa forja su leyenda como guerrera implacable. Esta precuela de Mad Max: Fury Road ofrece acción vertiginosa, paisajes desoladores y una historia de venganza y redención que define a una heroína inolvidable.', 2024, 150, 'George Miller', 'George Miller, Nico Lathouris', 'R', 'posters/Furiosa.jpg', 'Furiosa: De la Saga Mad Max', NULL, NULL, 8.6, 0, NOW(), NOW(), 1),
(18, 'Barbie', 'pelicula', 'Sé lo que quieras ser', 'Barbie, habitante de un mundo perfecto, se embarca en una aventura en el mundo real cuando enfrenta una crisis existencial. Acompañada por Ken, descubre las complejidades de la humanidad, el feminismo y la libertad de elegir su propio camino. Esta comedia vibrante y conmovedora combina humor, sátira y un mensaje poderoso sobre la identidad y el empoderamiento.', 2023, 114, 'Greta Gerwig', 'Greta Gerwig, Noah Baumbach', 'PG-13', 'posters/Barbie.jpg', 'Barbie', NULL, NULL, 8.2, 0, NOW(), NOW(), 1),
(19, 'Anatomía de una Caída', 'pelicula', '¿Culpable o inocente?', 'Sandra, una escritora de éxito, se convierte en la principal sospechosa tras la misteriosa muerte de su esposo. En un juicio que desentraña su matrimonio, su hijo ciego debe enfrentar la verdad sobre sus padres. Este thriller psicológico explora la ambigüedad de la verdad, las dinámicas familiares y los prejuicios, manteniendo al espectador al borde de la duda hasta el final.', 2023, 150, 'Justine Triet', 'Justine Triet, Arthur Harari', 'R', 'posters/AnatomiaDeUnaCaida.jpg', 'Anatomía de una Caída', NULL, NULL, 8.0, 0, NOW(), NOW(), 1),
(20, 'La Zona de Interés', 'pelicula', 'La banalidad del mal', 'Rudolf Höss, comandante de Auschwitz, y su familia llevan una vida idílica junto al campo de concentración. Mientras el horror ocurre a pocos metros, su rutina cotidiana revela una perturbadora indiferencia. Esta inquietante obra maestra examina la deshumanización, la complicidad silenciosa y el contraste entre la vida doméstica y las atrocidades inimaginables, dejando una huella imborrable sobre el costo moral de la ignorancia.', 2023, 105, 'Jonathan Glazer', 'Jonathan Glazer', 'PG-13', 'posters/la zona de interes.jpg', 'La Zona de Interés', NULL, NULL, 7.8, 0, NOW(), NOW(), 1),
(21, 'Godzilla y Kong: El Nuevo Imperio', 'pelicula', 'Dos titanes, un destino', 'Godzilla y Kong, antiguos rivales, deben unirse para enfrentar una amenaza colosal que emerge de la Tierra Hueca. Mientras los humanos descubren secretos ancestrales, los titanes libran una batalla épica que determinará el equilibrio del mundo. Esta aventura llena de acción combina espectaculares enfrentamientos con una exploración de la mitología de los monstruos más icónicos del cine.', 2024, 115, 'Adam Wingard', 'Terry Rossio, Simon Barrett', 'PG-13', 'posters/Godzilla y Kong El Nuevo Imperio.jpg', 'Godzilla y Kong: El Nuevo Imperio', NULL, NULL, 7.6, 0, NOW(), NOW(), 1),
(22, 'Los Asesinos de la Luna', 'pelicula', 'La codicia no tiene límites', 'En la Oklahoma de los años 20, los asesinatos de miembros de la nación Osage, enriquecida por el petróleo, desencadenan una investigación del naciente FBI. Este drama épico desentraña una red de codicia, traición y racismo, mientras explora el amor y la lealtad en un contexto de ambición desmedida. Basada en hechos reales, es un retrato inquietante de la injusticia.', 2023, 206, 'Martin Scorsese', 'Eric Roth, Martin Scorsese', 'R', 'posters/Los Asesinos de la Luna.jpg', 'Los Asesinos de la Luna', NULL, NULL, 7.4, 0, NOW(), NOW(), 1),
(23, 'Del Revés 2', 'pelicula', 'Nuevas emociones', 'Riley, ahora adolescente, enfrenta los retos de la pubertad mientras nuevas emociones, como Ansiedad, irrumpen en su mente. Alegría y el resto del equipo luchan por mantener el equilibrio en un torbellino de cambios. Esta encantadora secuela animada explora con humor y corazón los desafíos de crecer, la aceptación de uno mismo y la complejidad de las emociones humanas.', 2024, 96, 'Kelsey Mann', 'Meg LeFauve', 'PG', 'posters/DelReves2.jpg', 'Del Revés 2', NULL, NULL, 7.2, 0, NOW(), NOW(), 1),
(24, 'Wonka', 'pelicula', 'El origen del chocolate', 'El joven Willy Wonka, lleno de sueños y creatividad, se embarca en una aventura para abrir su primera tienda de chocolates. Enfrentando rivales y desafíos, su ingenio y magia transforman el mundo a su alrededor. Esta colorida precuela explora los orígenes del excéntrico chocolatero, celebrando la imaginación, la perseverancia y el dulce poder de hacer realidad los sueños.', 2023, 116, 'Paul King', 'Simon Farnaby, Paul King', 'PG', 'posters/Wonka.jpg', 'Wonka', NULL, NULL, 7.0, 0, NOW(), NOW(), 1),
(25, 'Aquaman y el Reino Perdido', 'pelicula', 'El océano en peligro', 'Arthur Curry, el rey de Atlantis, enfrenta una antigua amenaza que pone en peligro los siete mares. Aliado con su hermano Orm, debe forjar una alianza improbable para detener la destrucción. Esta aventura épica combina acción submarina, mitología y lealtades divididas, mientras Aquaman lucha por proteger su reino y el mundo de la superficie en una batalla de proporciones colosales.', 2023, 124, 'James Wan', 'David Leslie Johnson-McGoldrick', 'PG-13', 'posters/Aquaman.jpg', 'Aquaman y el Reino Perdido', NULL, NULL, 6.8, 0, NOW(), NOW(), 1),
(26, 'The Batman', 'pelicula', 'La venganza tiene un nuevo rostro', 'En una Gotham sumida en la corrupción, Bruce Wayne, en su segundo año como Batman, investiga una serie de asesinatos orquestados por el Acertijo. Mientras desentraña un complot que amenaza a la ciudad, enfrenta sus propios demonios. Este thriller oscuro y psicológico redefine al caballero de la noche con una intensidad visceral, explorando la justicia, la venganza y la esperanza en la oscuridad.', 2022, 176, 'Matt Reeves', 'Matt Reeves, Peter Craig', 'PG-13', 'posters/The Batman.webp', 'The Batman', NULL, NULL, 8.9, 0, NOW(), NOW(), 1),
(27, 'Parásitos', 'pelicula', 'La lucha de clases', 'La familia Kim, sumida en la pobreza, se infiltra astutamente en la vida de los ricos Park, haciéndose pasar por empleados calificados. Su plan desata una serie de eventos impredecibles que revelan las profundas desigualdades sociales. Este thriller satírico, cargado de humor negro y giros inesperados, explora la codicia, la moralidad y las barreras invisibles que dividen a la sociedad.', 2019, 132, 'Bong Joon-ho', 'Bong Joon-ho, Han Jin-won', 'R', 'posters/Parasite.jpg', 'Parásitos', NULL, NULL, 9.7, 0, NOW(), NOW(), 1),
(28, 'Spider-Man: A Través del Spider-Verso', 'pelicula', 'El multiverso se expande', 'Miles Morales, el joven Spider-Man, se lanza a una aventura a través de dimensiones paralelas, enfrentándose a un misterioso villano que amenaza la existencia de todos los universos. Junto a otros Spider-People, explora mundos vibrantes y únicos. Esta secuela animada combina arte innovador, acción trepidante y una emotiva historia sobre el sacrificio, la identidad y el poder de elegir tu propio destino.', 2023, 140, 'Joaquim Dos Santos, Kemp Powers', 'Phil Lord, Christopher Miller', 'PG', 'posters/Spider-Man a traves spiderverso.webp', 'Spider-Man: A Través del Spider-Verso', NULL, NULL, 9.5, 0, NOW(), NOW(), 1),
(29, 'Todo a la Vez en Todas Partes', 'pelicula', 'El multiverso es caótico', 'Evelyn Wang, una inmigrante china agotada por su lavandería y sus problemas familiares, descubre que puede conectarse con versiones de sí misma en universos paralelos. Enfrentando una amenaza multiversal, debe usar sus nuevas habilidades para salvar la realidad. Esta comedia surrealista y conmovedora explora la identidad, el amor familiar y la búsqueda de sentido en un caos infinito.', 2022, 139, 'Daniel Kwan, Daniel Scheinert', 'Daniel Kwan, Daniel Scheinert', 'R', 'posters/Todo a la vez en todas partes.jpg', 'Todo a la Vez en Todas Partes', NULL, NULL, 9.3, 0, NOW(), NOW(), 1),
(30, 'Top Gun: Maverick', 'pelicula', 'El regreso de Maverick', 'Pete "Maverick" Mitchell, un piloto legendario, regresa para entrenar a una nueva generación de aviadores en una misión de alto riesgo. Enfrentando su pasado y a un talentoso pero rebelde piloto, Maverick lidera un equipo en una operación que desafía los límites del coraje y la tecnología. Esta secuela llena de acción combina adrenalina aérea con una emotiva historia de redención.', 2022, 131, 'Joseph Kosinski', 'Ehren Kruger, Eric Warren Singer', 'PG-13', 'posters/Top Gun Maverick.webp', 'Top Gun: Maverick', NULL, NULL, 9.1, 0, NOW(), NOW(), 1),
(31, 'Joker', 'pelicula', 'Ríe y el mundo reirá contigo', 'Arthur Fleck, un comediante fracasado en una Gotham opresiva, lucha contra el abandono y la crueldad de la sociedad. Su descenso a la locura lo transforma en el icónico Joker, desencadenando un caos que sacude la ciudad. Este drama psicológico, oscuro y provocador, explora la alienación, la desesperación y los orígenes de un villano que redefine el crimen y la rebelión.', 2019, 122, 'Todd Phillips', 'Todd Phillips, Scott Silver', 'R', 'posters/Joker (2019).jpg', 'Joker', NULL, NULL, 8.7, 0, NOW(), NOW(), 1),
(32, 'Origen', 'pelicula', 'Tu mente es la escena del crimen', 'Dom Cobb, un ladrón especializado en infiltrarse en sueños, recibe el encargo definitivo: implantar una idea en la mente de una persona mientras duerme. Con un equipo de expertos, enfrenta un laberinto de sueños dentro de sueños, donde el tiempo, la realidad y el peligro se distorsionan. Este thriller de ciencia ficción explora la mente humana y los límites de la percepción.', 2010, 148, 'Christopher Nolan', 'Christopher Nolan', 'PG-13', 'posters/Origen.webp', 'Origen', NULL, NULL, 9.0, 0, NOW(), NOW(), 1),
(33, 'El Caballero Oscuro', 'pelicula', 'El caballero de Gotham', 'Batman enfrenta su mayor desafío cuando el Joker desata el caos en Gotham con un plan para destruir el orden y la esperanza. Mientras el fiscal Harvey Dent lucha por la justicia, Bruce Wayne debe confrontar los límites de su moralidad. Este thriller épico combina acción, intriga y dilemas éticos, redefiniendo el género de superhéroes con una intensidad inolvidable.', 2008, 152, 'Christopher Nolan', 'Jonathan Nolan, Christopher Nolan', 'PG-13', 'posters/CaballeroOscuro.webp', 'El Caballero Oscuro', NULL, NULL, 9.8, 0, NOW(), NOW(), 1),
(34, 'Interstellar', 'pelicula', 'El destino de la humanidad está en las estrellas', 'En un futuro donde la Tierra agoniza, Cooper, un ex-piloto, lidera una misión para encontrar un nuevo hogar para la humanidad a través de un agujero de gusano. Enfrentando sacrificios personales y fenómenos cósmicos, el equipo lucha contra el tiempo y el espacio. Este drama de ciencia ficción explora el amor, la supervivencia y la búsqueda de esperanza en lo desconocido.', 2014, 169, 'Christopher Nolan', 'Jonathan Nolan, Christopher Nolan', 'PG-13', 'posters/Interestellar.jpg', 'Interstellar', NULL, NULL, 9.5, 0, NOW(), NOW(), 1),
(35, 'El Club de la Pelea', 'pelicula', 'La primera regla es...', 'Un oficinista desencantado y un carismático desconocido crean un club secreto donde los hombres liberan sus frustraciones a puñetazos. Lo que comienza como una rebelión contra la monotonía se convierte en un movimiento caótico que desafía el orden social. Este thriller satírico y psicológico explora la identidad, el consumismo y la rebelión, dejando una marca imborrable con su audacia y provocación.', 1999, 139, 'David Fincher', 'Jim Uhls', 'R', 'posters/El Club de la Pelea.webp', 'El Club de la Pelea', NULL, NULL, 9.3, 0, NOW(), NOW(), 1),
(36, 'Tiempos Violentos', 'pelicula', 'Historias entrelazadas', 'En Los Ángeles, las vidas de un boxeador, dos sicarios, un gánster y su esposa se cruzan en una serie de historias entrelazadas llenas de crimen, redención y caos. Con diálogos ingeniosos y una narrativa no lineal, esta obra maestra de Quentin Tarantino combina violencia estilizada, humor negro y personajes inolvidables en un retrato vibrante de la vida al margen de la ley.', 1994, 154, 'Quentin Tarantino', 'Quentin Tarantino, Roger Avary', 'R', 'posters/Tiempos Violentos.jpg', 'Tiempos Violentos', NULL, NULL, 9.4, 0, NOW(), NOW(), 1),
(37, 'Cadena Perpetua', 'pelicula', 'La esperanza es algo peligroso', 'Andy Dufresne, un banquero condenado injustamente por asesinato, llega a la prisión de Shawshank, donde forja una improbable amistad con Red. A través de décadas de adversidad, su ingenio y esperanza desafían un sistema opresivo. Este drama conmovedor, basado en un relato de Stephen King, celebra la resiliencia humana, la redención y el poder transformador de la amistad frente a la injusticia.', 1994, 142, 'Frank Darabont', 'Frank Darabont', 'R', 'posters/Cadena Perpetua.jpg', 'Cadena Perpetua', NULL, NULL, 9.8, 0, NOW(), NOW(), 1),
(38, 'El Padrino', 'pelicula', 'El poder lo es todo', 'En la Nueva York de los años 40, la familia Corleone, liderada por Don Vito, navega el mundo del crimen organizado. Cuando una traición amenaza su imperio, Michael, el hijo menor, se ve arrastrado a un camino de poder y violencia. Este drama épico explora la lealtad, el legado y el costo moral de la ambición en una saga mafiosa inolvidable.', 1972, 175, 'Francis Ford Coppola', 'Mario Puzo, Francis Ford Coppola', 'R', 'posters/El Padrino.jpg', 'El Padrino', NULL, NULL, 9.7, 0, NOW(), NOW(), 1),
(39, 'Forrest Gump', 'pelicula', 'La vida es como una caja de bombones', 'Forrest Gump, un hombre sencillo con un corazón puro, vive una vida extraordinaria a través de décadas de cambios en Estados Unidos. Desde su infancia hasta convertirse en héroe, corredor y empresario, su amor por Jenny y su bondad inquebrantable lo guían. Esta conmovedora historia celebra la resiliencia, el destino y la belleza de la humanidad en un mundo impredecible.', 1994, 142, 'Robert Zemeckis', 'Eric Roth', 'PG-13', 'posters/Forrest Gump.jpg', 'Forrest Gump', NULL, NULL, 9.3, 0, NOW(), NOW(), 1),
(40, 'El Señor de los Anillos: La Comunidad del Anillo', 'pelicula', 'Un anillo para gobernarlos a todos', 'Frodo, un joven hobbit, hereda un anillo que encierra un poder oscuro. Junto a una comunidad de héroes, incluidos Gandalf, Aragorn y Legolas, emprende un peligroso viaje para destruirlo y evitar que caiga en manos del malvado Sauron. Esta épica aventura combina magia, valentía y amistad en un mundo fantástico al borde de la guerra.', 2001, 178, 'Peter Jackson', 'Fran Walsh, Philippa Boyens', 'PG-13', 'posters/El Señor de los Anillos 1 La Comunidad del Anillo.jpg', 'El Señor de los Anillos: La Comunidad del Anillo', NULL, NULL, 9.4, 0, NOW(), NOW(), 1),
(41, 'Matrix', 'pelicula', 'La realidad es una ilusión', 'Neo, un hacker, descubre que el mundo es una simulación controlada por máquinas. Guiado por Morfeo y Trinity, se une a la resistencia para despertar a la humanidad y enfrentar a los agentes de la Matrix. Este revolucionario thriller de ciencia ficción combina acción, filosofía y efectos visuales innovadores, cuestionando la realidad y el poder de la elección en un mundo digital.', 1999, 136, 'Lana Wachowski, Lilly Wachowski', 'Lana Wachowski, Lilly Wachowski', 'R', 'posters/Matrix.jpg', 'Matrix', NULL, NULL, 9.0, 0, NOW(), NOW(), 1),
(42, 'Gladiador', 'pelicula', 'Fuerza y honor', 'Maximus, un general romano traicionado, es esclavizado y convertido en gladiador tras la muerte de su familia. En la arena, su fuerza y carisma lo convierten en un símbolo de resistencia contra un emperador corrupto. Este drama épico combina acción visceral, venganza y redención, mientras Maximus lucha por la justicia y la libertad en un Imperio Romano al borde del caos.', 2000, 155, 'Ridley Scott', 'David Franzoni, John Logan', 'R', 'posters/Gladiador (2000).jpg', 'Gladiador', NULL, NULL, 8.9, 0, NOW(), NOW(), 1),
(43, 'Siete', 'pelicula', 'Los siete pecados capitales', 'Dos detectives, el veterano Somerset y el impulsivo Mills, persiguen a un asesino en serie que usa los siete pecados capitales como inspiración para sus crímenes. En una ciudad oscura y opresiva, cada caso los lleva más cerca de un final inquietante. Este thriller psicológico combina suspenso, horror y dilemas morales, dejando una marca imborrable con su atmósfera sombría y giros devastadores.', 1995, 127, 'David Fincher', 'Andrew Kevin Walker', 'R', 'posters/Siete (1995).jpg', 'Siete', NULL, NULL, 9.2, 0, NOW(), NOW(), 1),
(44, 'Rescatando al Soldado Ryan', 'pelicula', 'La guerra tiene un precio', 'Tras el desembarco de Normandía, el capitán Miller lidera un escuadrón en una peligrosa misión para rescatar al soldado Ryan, el último superviviente de cuatro hermanos. Enfrentando los horrores de la Segunda Guerra Mundial, el equipo cuestiona el valor de una vida frente al sacrificio colectivo. Este drama bélico ofrece acción cruda y una profunda reflexión sobre el deber y la humanidad.', 1998, 169, 'Steven Spielberg', 'Robert Rodat', 'R', 'posters/Rescatando al Soldado Ryan.jpg', 'Rescatando al Soldado Ryan', NULL, NULL, 9.0, 0, NOW(), NOW(), 1),
(45, 'El Rey León', 'pelicula', 'Siente el rugido', 'Simba, un cachorro de león destinado a gobernar, huye tras una tragedia familiar orquestada por su tío Scar. Criado por un dúo improbable, Timón y Pumba, regresa para enfrentar su pasado y reclamar su lugar como rey. Esta joya animada combina humor, música y una emotiva historia sobre el crecimiento, la responsabilidad y el ciclo eterno de la vida.', 1994, 89, 'Roger Allers, Rob Minkoff', 'Irene Mecchi, Jonathan Roberts', 'G', 'posters/El Rey León (1994).jpg', 'El Rey León', NULL, NULL, 8.8, 0, NOW(), NOW(), 1),
(46, 'Regreso al Futuro', 'pelicula', 'Nunca llegaba a tiempo a clase', 'Marty McFly, un adolescente, viaja accidentalmente a 1955 en un DeLorean modificado por el excéntrico Doc Brown. Para regresar a 1985, debe asegurar que sus padres se enamoren mientras evita alterar el futuro. Esta aventura de ciencia ficción combina humor, acción y nostalgia, explorando el destino, la familia y las consecuencias de jugar con el tiempo en un viaje inolvidable.', 1985, 116, 'Robert Zemeckis', 'Robert Zemeckis, Bob Gale', 'PG', 'posters/regreso al futuro.jpg', 'Volver al Futuro', NULL, NULL, 9.0, 0, NOW(), NOW(), 1),
(47, 'El Silencio de los Corderos', 'pelicula', 'El mal tiene muchas caras', 'Clarice Starling, una joven agente del FBI, busca la ayuda del brillante pero aterrador Hannibal Lecter para capturar a un asesino en serie conocido como Buffalo Bill. En un juego psicológico de astucia y manipulación, Clarice enfrenta sus miedos mientras desentraña un caso macabro. Este thriller icónico combina suspenso, horror y personajes inolvidables en una cacería implacable.', 1991, 118, 'Jonathan Demme', 'Ted Tally', 'R', 'posters/El_silencio_de_los_corderos.jpg', 'El Silencio de los Corderos', NULL, NULL, 9.2, 0, NOW(), NOW(), 1),
(48, 'Jurassic Park', 'pelicula', 'La vida se abre camino', 'Un excéntrico millonario crea un parque temático con dinosaurios clonados en una isla remota. Cuando un fallo de seguridad desata el caos, un grupo de visitantes, incluidos un paleontólogo y dos niños, lucha por sobrevivir entre criaturas prehistóricas. Este clásico de ciencia ficción combina maravilla, tensión y efectos visuales revolucionarios, explorando la arrogancia humana frente al poder de la naturaleza.', 1993, 127, 'Steven Spielberg', 'Michael Crichton, David Koepp', 'PG-13', 'posters/Jurassic Park.jpg', 'Parque Jurásico', NULL, NULL, 9.1, 0, NOW(), NOW(), 1),
(49, 'La Lista de Schindler', 'pelicula', 'El valor de una vida', 'Oskar Schindler, un empresario alemán, transforma su ambición en una misión para salvar a más de mil judíos durante el Holocausto, arriesgando todo en un acto de humanidad. Este drama histórico, basado en hechos reales, retrata el horror del genocidio y el poder de la compasión, dejando una profunda reflexión sobre el sacrificio y la esperanza en tiempos de oscuridad.', 1993, 195, 'Steven Spielberg', 'Steven Zaillian', 'R', 'posters/La_lista_de_Schindler.jpg', 'La Lista de Schindler', NULL, NULL, 9.7, 0, NOW(), NOW(), 1),
(50, 'El Indomable Will Hunting', 'pelicula', 'El genio está en todas partes', 'Will Hunting, un joven conserje con un intelecto prodigioso para las matemáticas, oculta su talento tras un pasado turbulento. Cuando un profesor lo descubre, un terapeuta poco convencional lo ayuda a enfrentar sus demonios emocionales. Este drama conmovedor explora la genialidad, la vulnerabilidad y la búsqueda de propósito, destacando el poder transformador de la conexión humana y el autodescubrimiento.', 1997, 126, 'Gus Van Sant', 'Matt Damon, Ben Affleck', 'R', 'posters/El Indomable Will Hunting (1997).jpg', 'El Indomable Will Hunting', NULL, NULL, 9.0, 0, NOW(), NOW(), 1),
(51, 'Infiltrados', 'pelicula', '¿Quién es el topo?', 'En Boston, un policía encubierto, Billy Costigan, se infiltra en la mafia irlandesa, mientras un criminal, Colin Sullivan, se convierte en topo dentro de la policía. Sus caminos se cruzan en un juego mortal de engaño y traición. Este thriller intenso de Martin Scorsese combina suspenso, intriga y actuaciones magistrales, explorando la lealtad y el costo de vivir una doble vida.', 2006, 151, 'Martin Scorsese', 'William Monahan', 'R', 'posters/infiltrados.jpg', 'Infiltrados', NULL, NULL, 9.1, 0, NOW(), NOW(), 1),
(52, 'Avatar 2', 'pelicula', 'El camino del agua', 'Jake Sully y Neytiri, ahora padres, enfrentan nuevas amenazas en Pandora mientras protegen a su familia. Explorando océanos y culturas desconocidas, se unen a los clanes Na’vi para combatir una invasión humana renovada. Esta secuela épica combina espectaculares paisajes acuáticos, acción y una emotiva historia sobre la familia, la resistencia y la conexión con la naturaleza.', 2022, 192, 'James Cameron', 'James Cameron', 'PG-13', 'posters/Avatar2.jpg', 'Avatar 2', NULL, NULL, 9.0, 0, NOW(), NOW(), 1),
(53, 'Deadpool y Wolverine', 'pelicula', 'El dúo más irreverente', 'Deadpool, el mercenario bocazas, une fuerzas con un Wolverine renuente en una misión multiversal llena de caos y humor. Enfrentando enemigos extravagantes y rompiendo la cuarta pared, este dúo improbable combina acción explosiva, bromas irreverentes y una sorprendente camaradería, mientras intentan salvar su realidad en una aventura que redefine la amistad y la redención.', 2024, 128, 'Shawn Levy', 'Rhett Reese, Paul Wernick', 'R', 'posters/Deadpool y Wolverine (2024).jpg', 'Deadpool y Wolverine', NULL, NULL, 8.7, 0, NOW(), NOW(), 1),
(54, 'Sin Lugar para los Débiles', 'pelicula', 'El destino está escrito', 'Llewelyn Moss encuentra una maleta llena de dinero en una escena de crimen en el desierto, desencadenando una persecución implacable por parte de Anton Chigurh, un asesino psicopático. En un juego mortal de gato y ratón, este thriller de los hermanos Coen explora el destino, la moralidad y la violencia en un paisaje desolado donde nadie está a salvo.', 2007, 122, 'Joel Coen, Ethan Coen', 'Joel Coen, Ethan Coen', 'R', 'posters/Sin Lugar para los Débiles (2007).jpg', 'Sin Lugar para los Débiles', NULL, NULL, 9.0, 0, NOW(), NOW(), 1),
(55, 'La La Land', 'pelicula', 'Haz realidad tus sueños', 'Mia, una aspirante a actriz, y Sebastian, un pianista de jazz, se enamoran en Los Ángeles mientras persiguen sus sueños. Su romance se enfrenta a los sacrificios que exige la ambición en una ciudad de ilusiones. Esta vibrante historia musical combina números espectaculares, emoción y una reflexión agridulce sobre el amor, el arte y las decisiones que definen la vida.', 2016, 128, 'Damien Chazelle', 'Damien Chazelle', 'PG-13', 'posters/Lalaland.jpg', 'La La Land', NULL, NULL, 8.5, 0, NOW(), NOW(), 1),
(56, 'Coco', 'pelicula', 'Recuerda a tu familia', 'Miguel, un niño mexicano con sueños de ser músico, se adentra accidentalmente en la vibrante Tierra de los Muertos. Allí, descubre secretos de su familia y la importancia de honrar a sus ancestros. Esta colorida aventura animada celebra la cultura mexicana, la música y los lazos familiares, entregando una historia conmovedora sobre la memoria, el legado y el poder de seguir tus pasiones.', 2017, 105, 'Lee Unkrich', 'Adrian Molina, Matthew Aldrich', 'PG', 'posters/Coco.jpeg', 'Coco', NULL, NULL, 8.7, 0, NOW(), NOW(), 1),
(57, 'Gravity', 'pelicula', 'No hay nada que temer allá afuera', 'La Dra. Ryan Stone y el astronauta Matt Kowalski quedan varados en el espacio tras un accidente que destruye su transbordador. Enfrentando la soledad y el vacío infinito, luchan por sobrevivir contra el tiempo y las adversidades. Este thriller visualmente impactante combina tensión, efectos revolucionarios y una profunda exploración de la resiliencia humana frente al aislamiento y la desesperación.', 2013, 91, 'Alfonso Cuarón', 'Alfonso Cuarón, Jonás Cuarón', 'PG-13', 'posters/Gravity.jpg', 'Gravity', NULL, NULL, 8.1, 0, NOW(), NOW(), 1),
(58, 'El Gran Hotel Budapest', 'pelicula', 'Una aventura inolvidable', 'En los años 30, Gustave, un excéntrico conserje, y Zero, su joven protegido, se ven envueltos en una intriga tras la muerte de una huésped adinerada. Entre robos, persecuciones y un valioso cuadro, esta comedia estilizada de Wes Anderson combina humor extravagante, personajes coloridos y una estética única, explorando la lealtad y la nostalgia en un mundo en declive.', 2014, 99, 'Wes Anderson', 'Wes Anderson, Hugo Guinness', 'R', 'posters/ElGranHotelBudapest.jpg', 'El Gran Hotel Budapest', NULL, NULL, 8.4, 0, NOW(), NOW(), 1),
(59, 'Black Panther', 'pelicula', 'Wakanda por siempre', 'T’Challa, el nuevo rey de Wakanda, debe proteger su nación tecnológicamente avanzada de amenazas internas y externas tras la muerte de su padre. Como Black Panther, enfrenta a un rival que desafía su liderazgo y los secretos del reino. Esta épica de superhéroes combina acción, cultura africana y temas de identidad, ofreciendo un vibrante homenaje al legado y la responsabilidad.', 2018, 134, 'Ryan Coogler', 'Ryan Coogler, Joe Robert Cole', 'PG-13', 'posters/Black Panther.jpg', 'Black Panther', NULL, NULL, 8.0, 0, NOW(), NOW(), 1),
(60, 'El Gran Pez', 'pelicula', 'Una vida de historias', 'Will Bloom intenta descifrar la verdad detrás de las fantásticas historias de su padre, Edward, un hombre cuya vida está llena de relatos extraordinarios. A través de cuentos de gigantes, brujas y amores épicos, esta fábula de Tim Burton explora la relación entre padre e hijo, la magia de la narrativa y la búsqueda de significado en una vida llena de imaginación.', 2003, 125, 'Tim Burton', 'John August', 'PG-13', 'posters/El_Gran_Pez_-_Poster.webp', 'El Gran Pez', NULL, NULL, 8.2, 0, NOW(), NOW(), 1);


-- Inserción de plataformas de streaming y vinculación con películas

-- Plataformas (sin vinculación inicial a contenido)
INSERT INTO plataformas_streaming (id_plataforma, id_contenido_id, nombre_plataforma, imagen_logo_plataforma, alt_imagen_logo_plataforma, tipo_acceso, precio, creador_id)
VALUES
(1, NULL, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
(2, NULL, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
(3, NULL, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
(4, NULL, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1);

-- Vinculación de películas con plataformas
INSERT INTO plataformas_streaming (id_plataforma, id_contenido, nombre_plataforma, imagen_logo_plataforma, alt_imagen_logo_plataforma, tipo_acceso, precio, creador_id)
VALUES
-- Avatar (Netflix, Disney+)
(5, 1, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
(6, 1, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Avengers: Endgame (Disney+)
(7, 2, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Titanic (Netflix)
(8, 3, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Star Wars: The Force Awakens (Disney+)
(9, 4, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Jurassic World (Netflix)
(10, 5, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- The Lion King (Disney+)
(11, 6, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- The Avengers (Disney+, Netflix)
(12, 7, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
(13, 7, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Furious 7 (Netflix)
(14, 8, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Frozen II (Disney+)
(15, 9, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Beauty and the Beast (Disney+)
(16, 10, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Dune: Parte 2 (HBO Max)
(17, 11, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- Oppenheimer (Netflix)
(18, 12, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Pobres Criaturas (HBO Max)
(19, 13, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- Civil War (Prime Video)
(20, 14, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Rivales (Prime Video)
(21, 15, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- El Planeta de los Simios: Nuevo Reino (Disney+)
(22, 16, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Furiosa: De la Saga Mad Max (Prime Video)
(23, 17, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Barbie (Netflix, HBO Max)
(24, 18, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
(25, 18, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- Anatomía de una Caída (Prime Video)
(26, 19, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- La Zona de Interés (Prime Video)
(27, 20, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Godzilla y Kong: El Nuevo Imperio (HBO Max)
(28, 21, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- Los Asesinos de la Luna (Prime Video)
(29, 22, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Del Revés 2 (Disney+)
(30, 23, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Wonka (HBO Max)
(31, 24, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- Aquaman y el Reino Perdido (HBO Max)
(32, 25, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- The Batman (HBO Max)
(33, 26, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- Parásitos (Netflix)
(34, 27, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Spider-Man: A Través del Spider-Verso (Netflix)
(35, 28, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Todo a la Vez en Todas Partes (Prime Video)
(36, 29, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Top Gun: Maverick (Prime Video)
(37, 30, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Joker (Netflix)
(38, 31, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Origen (Netflix, HBO Max)
(39, 32, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
(40, 32, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- El Caballero Oscuro (HBO Max)
(41, 33, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- Interstellar (HBO Max)
(42, 34, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- El Club de la Pelea (Prime Video)
(43, 35, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Tiempos Violentos (Prime Video)
(44, 36, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Cadena Perpetua (Netflix)
(45, 37, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- El Padrino (Prime Video)
(46, 38, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Forrest Gump (Netflix)
(47, 39, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- El Señor de los Anillos: La Comunidad del Anillo (Prime Video)
(48, 40, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Matrix (Netflix, HBO Max)
(49, 41, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
(50, 41, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- Gladiador (Prime Video)
(51, 42, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Siete (Netflix)
(52, 43, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Rescatando al Soldado Ryan (Prime Video)
(53, 44, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- El Rey León (Disney+)
(54, 45, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Regreso al Futuro (Prime Video)
(55, 46, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- El Silencio de los Corderos (Prime Video)
(56, 47, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Jurassic Park (Netflix)
(57, 48, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- La Lista de Schindler (Prime Video)
(58, 49, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- El Indomable Will Hunting (Prime Video)
(59, 50, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Infiltrados (Prime Video)
(60, 51, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Avatar 2 (Disney+)
(61, 52, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Deadpool y Wolverine (Disney+)
(62, 53, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Sin Lugar para los Débiles (Prime Video)
(63, 54, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- La La Land (Netflix)
(64, 55, 'Netflix', 'logos/netflix.jpg', 'Logo de Netflix', 'suscripción', 9.99, 1),
-- Coco (Disney+)
(65, 56, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- Gravity (HBO Max)
(66, 57, 'HBO Max', 'logos/hbomax.jpeg', 'Logo de HBO Max', 'suscripción', 9.99, 1),
-- El Gran Hotel Budapest (Prime Video)
(67, 58, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1),
-- Black Panther (Disney+)
(68, 59, 'Disney+', 'logos/disneyplus.jpg', 'Logo de Disney+', 'suscripción', 9.99, 1),
-- El Gran Pez (Prime Video)
(69, 60, 'Prime Video', 'logos/primevideo.jpg', 'Logo de Prime Video', 'suscripción', 9.99, 1);