-- 3. Actores
INSERT INTO actor (id_actor, nombre_actor, imagen_actor, creador_id) VALUES
(1, 'Sam Worthington', 'actores/Sam Worthington.jpg', 1),
(2, 'Zoe Saldana', 'actores/Zoe Saldana.webp', 1),
(3, 'Sigourney Weaver', 'actores/Sigourney Weaver.jpg', 1),
(4, 'Stephen Lang', 'actores/Stephen Lang.jpg', 1),
(5, 'Robert Downey Jr.', 'actores/Robert Downey Jr..webp', 1),
(6, 'Chris Evans', 'actores/Chris Evans.jpg', 1),
(7, 'Scarlett Johansson', 'actores/Scarlett Johansson.jpg', 1),
(8, 'Chris Hemsworth', 'actores/Chris Hemsworth.jpg', 1),
(9, 'Leonardo DiCaprio', 'actores/Leonardo DiCaprio.webp', 1),
(10, 'Kate Winslet', 'actores/Kate Winslet.webp', 1),
(11, 'Billy Zane', 'actores/Billy Zane.jpg', 1),
(12, 'Kathy Bates', 'actores/Kathy Bates.jpg', 1),
(13, 'Daisy Ridley', 'actores/Daisy Ridley.jpg', 1),
(14, 'John Boyega', 'actores/John Boyega.webp', 1),
(15, 'Harrison Ford', 'actores/Harrison Ford.webp', 1),
(16, 'Adam Driver', 'actores/Adam Driver.jpg', 1),
(17, 'Chris Pratt', 'actores/Chris Pratt.webp', 1),
(18, 'Bryce Dallas Howard', 'actores/Bryce Dallas Howard.webp', 1),
(19, 'Vincent D''Onofrio', 'actores/Vincent D Onofrio.jpg', 1),
(20, 'Irrfan Khan', 'actores/Irrfan Khan.jpg', 1),
(21, 'Donald Glover', 'actores/Donald Glover.webp', 1),
(22, 'Beyoncé', 'actores/Beyoncé.jpg', 1),
(23, 'James Earl Jones', 'actores/James Earl Jones.jpg', 1),
(24, 'Chiwetel Ejiofor', 'actores/Chiwetel Ejiofor.jpg', 1),
(25, 'Vin Diesel', 'actores/Vin Diesel.webp', 1),
(26, 'Paul Walker', 'actores/Paul Walker.jpg', 1),
(27, 'Dwayne Johnson', 'actores/Dwayne Johnson.jpg', 1),
(28, 'Michelle Rodriguez', 'actores/Michelle Rodriguez.jpg', 1),
(29, 'Idina Menzel', 'actores/Idina Menzel.jpg', 1),
(30, 'Kristen Bell', 'actores/Kristen Bell.jpg', 1),
(31, 'Josh Gad', 'actores/Josh Gad.jpg', 1),
(32, 'Jonathan Groff', 'actores/Jonathan Groff.jpg', 1),
(33, 'Emma Watson', 'actores/Emma Watson.webp', 1),
(34, 'Dan Stevens', 'actores/Dan Stevens.jpg', 1),
(35, 'Luke Evans', 'actores/Luke Evans.jpg', 1),
(36, 'Timothée Chalamet', 'actores/Timothée Chalamet.jpg', 1),
(37, 'Zendaya', 'actores/Zendaya.webp', 1),
(38, 'Rebecca Ferguson', 'actores/Rebecca Ferguson.webp', 1),
(39, 'Josh Brolin', 'actores/Josh Brolin.jpg', 1),
(40, 'Cillian Murphy', 'actores/Cillian Murphy.webp', 1),
(41, 'Emily Blunt', 'actores/Emily Blunt.png', 1),
(42, 'Matt Damon', 'actores/Matt Damon.jpg', 1),
(43, 'Emma Stone', 'actores/Emma Stone.jpg', 1),
(44, 'Mark Ruffalo', 'actores/Mark Ruffalo.jpg', 1),
(45, 'Willem Dafoe', 'actores/Willem Dafoe.webp', 1),
(46, 'Ramy Youssef', 'actores/Ramy Youssef.png', 1),
(47, 'Kirsten Dunst', 'actores/Kirsten Dunst.jpg', 1),
(48, 'Cailee Spaeny', 'actores/Cailee Spaeny.jpg', 1),
(49, 'Wagner Moura', 'actores/Wagner Moura.jpg', 1),
(50, 'Stephen McKinley Henderson', 'actores/Stephen McKinley Henderson.jpg', 1),
(51, 'Mike Faist', 'actores/Mike Faist.jpg', 1),
(52, 'Josh O''Connor', 'actores/Josh O Connor.jpg', 1),
(53, 'A.J. Lister', 'actores/A.J. Lister.jpg', 1),
(54, 'Owen Teague', 'actores/Owen Teague.jpg', 1),
(55, 'Freya Allan', 'actores/Freya Allan.jpg', 1),
(56, 'Kevin Durand', 'actores/Kevin Durand.jpg', 1),
(57, 'Peter Macon', 'actores/Peter Macon.jpg', 1),
(58, 'Anya Taylor-Joy', 'actores/Anya Taylor-Joy.jpg', 1),
(59, 'Tom Burke', 'actores/Tom Burke.jpg', 1),
(60, 'Nathan Jones', 'actores/Nathan Jones.jpg', 1),
(61, 'Margot Robbie', 'actores/Margot Robbie.jpg', 1),
(62, 'Ryan Gosling', 'actores/Ryan Gosling.jpg', 1),
(63, 'America Ferrera', 'actores/America Ferrera.jpg', 1),
(64, 'Kate McKinnon', 'actores/Kate McKinnon.jpg', 1),
(65, 'Sandra Hüller', 'actores/Sandra Hüller.jpg', 1),
(66, 'Swann Arlaud', 'actores/Swann Arlaud.jpg', 1),
(67, 'Milo Machado Graner', 'actores/Milo Machado Graner.jpg', 1),
(68, 'Antoine Reinartz', 'actores/Antoine Reinartz.jpg', 1),
(69, 'Christian Friedel', 'actores/Christian Friedel.jpg', 1),
(70, 'Freya Kreutzkam', 'actores/Freya Kreutzkam.jpg', 1),
(71, 'Ralph Herforth', 'actores/Ralph Herforth.jpg', 1),
(72, 'Rebecca Hall', 'actores/Rebecca Hall.jpg', 1),
(73, 'Brian Tyree Henry', 'actores/Brian Tyree Henry.jpg', 1),
(74, 'Kaylee Hottle', 'actores/Kaylee Hottle.webp', 1),
(75, 'Lily Gladstone', 'actores/Lily Gladstone.jpg', 1),
(76, 'Jesse Plemons', 'actores/Jesse Plemons.png', 1),
(77, 'Amy Poehler', 'actores/Amy Poehler.jpg', 1),
(78, 'Phyllis Smith', 'actores/Phyllis Smith.jpg', 1),
(79, 'Lewis Black', 'actores/Lewis Black.jpg', 1),
(80, 'Maya Hawke', 'actores/Maya Hawke.jpg', 1),
(81, 'Hugh Grant', 'actores/Hugh Grant.jpg', 1),
(82, 'Olivia Colman', 'actores/Olivia Colman.jpg', 1),
(83, 'Keegan-Michael Key', 'actores/Keegan-Michael Key.jpg', 1),
(84, 'Jason Momoa', 'actores/Jason Momoa.jpg', 1),
(85, 'Patrick Wilson', 'actores/Patrick Wilson.jpg', 1),
(86, 'Amber Heard', 'actores/Amber Heard.jpg', 1),
(87, 'Yahya Abdul-Mateen II', 'actores/Yahya Abdul-Mateen II.jpg', 1),
(88, 'Robert Pattinson', 'actores/Robert Pattinson.jpg', 1),
(89, 'Zoë Kravitz', 'actores/Zoë Kravitz.jpg', 1),
(90, 'Paul Dano', 'actores/Paul Dano.jpg', 1),
(91, 'Colin Farrell', 'actores/Colin Farrell.jpg', 1),
(92, 'Song Kang-ho', 'actores/Song Kang-ho.jpg', 1),
(93, 'Lee Sun-kyun', 'actores/Lee Sun-kyun.jpg', 1),
(94, 'Cho Yeo-jeong', 'actores/Cho Yeo-jeong.jpg', 1),
(95, 'Choi Woo-shik', 'actores/Choi Woo-shik.jpg', 1),
(96, 'Shameik Moore', 'actores/Shameik Moore.jpg', 1),
(97, 'Hailee Steinfeld', 'actores/Hailee Steinfeld.jpg', 1),
(98, 'Oscar Isaac', 'actores/Oscar Isaac.jpg', 1),
(99, 'Jake Johnson', 'actores/Jake Johnson.jpg', 1),
(100, 'Michelle Yeoh', 'actores/Michelle Yeoh.jpg', 1),
(101, 'Ke Huy Quan', 'actores/Ke Huy Quan.jpg', 1),
(102, 'Stephanie Hsu', 'actores/Stephanie Hsu.jpg', 1),
(103, 'James Hong', 'actores/James Hong.jpg', 1),
(104, 'Tom Cruise', 'actores/Tom Cruise.jpg', 1),
(105, 'Miles Teller', 'actores/Miles Teller.jpg', 1),
(106, 'Jennifer Connelly', 'actores/Jennifer Connelly.jpg', 1),
(107, 'Jon Hamm', 'actores/Jon Hamm.jpg', 1),
(108, 'Joaquin Phoenix', 'actores/Joaquin Phoenix.jpg', 1),
(109, 'Zazie Beetz', 'actores/Zazie Beetz.jpg', 1),
(110, 'Frances Conroy', 'actores/Frances Conroy.jpg', 1),
(111, 'Joseph Gordon-Levitt', 'actores/Joseph Gordon-Levitt.jpg', 1),
(112, 'Elliot Page', 'actores/Elliot Page.jpg', 1),
(113, 'Tom Hardy', 'actores/Tom Hardy.jpg', 1),
(114, 'Christian Bale', 'actores/Christian Bale.jpg', 1),
(115, 'Heath Ledger', 'actores/Heath Ledger.jpg', 1),
(116, 'Aaron Eckhart', 'actores/Aaron Eckhart.jpg', 1),
(117, 'Maggie Gyllenhaal', 'actores/Maggie Gyllenhaal.jpg', 1),
(118, 'Matthew McConaughey', 'actores/Matthew McConaughey.jpg', 1),
(119, 'Anne Hathaway', 'actores/Anne Hathaway.jpg', 1),
(120, 'Jessica Chastain', 'actores/Jessica Chastain.jpg', 1),
(121, 'Michael Caine', 'actores/Michael Caine.jpg', 1),
(122, 'Edward Norton', 'actores/Edward Norton.jpg', 1),
(123, 'Brad Pitt', 'actores/Brad Pitt.jpg', 1),
(124, 'Helena Bonham Carter', 'actores/Helena Bonham Carter.jpg', 1),
(125, 'Meat Loaf', 'actores/Meat Loaf.jpg', 1),
(126, 'John Travolta', 'actores/John Travolta.jpg', 1),
(127, 'Samuel L. Jackson', 'actores/Samuel L. Jackson.jpg', 1),
(128, 'Uma Thurman', 'actores/Uma Thurman.jpg', 1),
(129, 'Bruce Willis', 'actores/Bruce Willis.jpg', 1),
(130, 'Tim Robbins', 'actores/Tim Robbins.jpg', 1),
(131, 'Morgan Freeman', 'actores/Morgan Freeman.jpg', 1),
(132, 'Bob Gunton', 'actores/Bob Gunton.jpg', 1),
(133, 'William Sadler', 'actores/William Sadler.jpg', 1),
(134, 'Marlon Brando', 'actores/Marlon Brando.jpg', 1),
(135, 'Al Pacino', 'actores/Al Pacino.jpg', 1),
(136, 'James Caan', 'actores/James Caan.jpg', 1),
(137, 'Diane Keaton', 'actores/Diane Keaton.jpg', 1),
(138, 'Tom Hanks', 'actores/Tom Hanks.jpg', 1),
(139, 'Robin Wright', 'actores/Robin Wright.jpg', 1),
(140, 'Gary Sinise', 'actores/Gary Sinise.jpg', 1),
(141, 'Sally Field', 'actores/Sally Field.jpg', 1),
(142, 'Elijah Wood', 'actores/Elijah Wood.jpg', 1),
(143, 'Ian McKellen', 'actores/Ian McKellen.jpg', 1),
(144, 'Viggo Mortensen', 'actores/Viggo Mortensen.jpg', 1),
(145, 'Sean Astin', 'actores/Sean Astin.jpg', 1),
(146, 'Keanu Reeves', 'actores/Keanu Reeves.jpg', 1),
(147, 'Laurence Fishburne', 'actores/Laurence Fishburne.jpg', 1),
(148, 'Carrie-Anne Moss', 'actores/Carrie-Anne Moss.jpg', 1),
(149, 'Hugo Weaving', 'actores/Hugo Weaving.jpg', 1),
(150, 'Russell Crowe', 'actores/Russell Crowe.jpg', 1),
(151, 'Connie Nielsen', 'actores/Connie Nielsen.jpg', 1),
(152, 'Oliver Reed', 'actores/Oliver Reed.jpg', 1),
(153, 'Gwyneth Paltrow', 'actores/Gwyneth Paltrow.jpg', 1),
(154, 'Kevin Spacey', 'actores/Kevin Spacey.jpg', 1),
(155, 'Tom Sizemore', 'actores/Tom Sizemore.jpg', 1),
(156, 'Edward Burns', 'actores/Edward Burns.jpg', 1),
(157, 'Matthew Broderick', 'actores/Matthew Broderick.jpg', 1),
(158, 'Jeremy Irons', 'actores/Jeremy Irons.jpg', 1),
(159, 'Moira Kelly', 'actores/Moira Kelly.jpg', 1),
(160, 'Michael J. Fox', 'actores/Michael J. Fox.jpg', 1),
(161, 'Christopher Lloyd', 'actores/Christopher Lloyd.jpg', 1),
(162, 'Lea Thompson', 'actores/Lea Thompson.jpg', 1),
(163, 'Crispin Glover', 'actores/Crispin Glover.jpg', 1),
(164, 'Jodie Foster', 'actores/Jodie Foster.jpg', 1),
(165, 'Anthony Hopkins', 'actores/Anthony Hopkins.jpg', 1),
(166, 'Scott Glenn', 'actores/Scott Glenn.jpg', 1),
(167, 'Ted Levine', 'actores/Ted Levine.jpg', 1),
(168, 'Sam Neill', 'actores/Sam Neill.jpg', 1),
(169, 'Laura Dern', 'actores/Laura Dern.jpg', 1),
(170, 'Jeff Goldblum', 'actores/Jeff Goldblum.jpg', 1),
(171, 'Richard Attenborough', 'actores/Richard Attenborough.jpg', 1),
(172, 'Liam Neeson', 'actores/Liam Neeson.jpg', 1),
(173, 'Ben Kingsley', 'actores/Ben Kingsley.jpg', 1),
(174, 'Ralph Fiennes', 'actores/Ralph Fiennes.jpg', 1),
(175, 'Caroline Goodall', 'actores/Caroline Goodall.jpg', 1),
(176, 'Robin Williams', 'actores/Robin Williams.jpg', 1),
(177, 'Ben Affleck', 'actores/Ben Affleck.jpg', 1),
(178, 'Stellan Skarsgård', 'actores/Stellan Skarsgård.jpg', 1),
(179, 'Mark Wahlberg', 'actores/Mark Wahlberg.jpg', 1),
(180, 'Ryan Reynolds', 'actores/Ryan Reynolds.jpg', 1),
(181, 'Hugh Jackman', 'actores/Hugh Jackman.jpg', 1),
(182, 'Emma Corrin', 'actores/Emma Corrin.jpg', 1),
(183, 'Matthew Macfadyen', 'actores/Matthew Macfadyen.jpg', 1),
(184, 'Javier Bardem', 'actores/Javier Bardem.jpg', 1),
(185, 'Tommy Lee Jones', 'actores/Tommy Lee Jones.jpg', 1),
(186, 'Kelly Macdonald', 'actores/Kelly Macdonald.jpg', 1),
(187, 'John Legend', 'actores/John Legend.jpg', 1),
(188, 'Rosemarie DeWitt', 'actores/Rosemarie DeWitt.jpg', 1),
(189, 'Anthony Gonzalez', 'actores/Anthony Gonzalez.jpg', 1),
(190, 'Gael García Bernal', 'actores/Gael García Bernal.jpg', 1),
(191, 'Benjamin Bratt', 'actores/Benjamin Bratt.jpg', 1),
(192, 'Alanna Ubach', 'actores/Alanna Ubach.jpg', 1),
(193, 'Sandra Bullock', 'actores/Sandra Bullock.jpg', 1),
(194, 'George Clooney', 'actores/George Clooney.jpg', 1),
(195, 'Ed Harris', 'actores/Ed Harris.jpg', 1),
(196, 'Orto Ignatiussen', 'actores/Orto Ignatiussen.jpg', 1),
(197, 'Tony Revolori', 'actores/Tony Revolori.jpg', 1),
(198, 'Saoirse Ronan', 'actores/Saoirse Ronan.jpg', 1),
(199, 'Adrien Brody', 'actores/Adrien Brody.jpg', 1),
(200, 'Chadwick Boseman', 'actores/Chadwick Boseman.jpg', 1),
(201, 'Michael B. Jordan', 'actores/Michael B. Jordan.jpg', 1),
(202, 'Lupita Nyong`o', 'actores/Lupita Nyong o.jpg', 1),
(203, 'Danai Gurira', 'actores/Danai Gurira.jpg', 1),
(204, 'Ewan McGregor', 'actores/Ewan McGregor.jpg', 1),
(205, 'Albert Finney', 'actores/Albert Finney.jpg', 1),
(206, 'Billy Crudup', 'actores/Billy Crudup.jpg', 1),
(207, 'Jessica Lange', 'actores/Jessica Lange.jpg', 1),
(208, 'Emilia Clarke', 'actores/Emilia Clarke.jpg', 1),
(209, 'Kit Harington', 'actores/Kit Harington.jpg', 1),
(210, 'Peter Dinklage', 'actores/Peter Dinklage.jpg', 1),
(211, 'Lena Headey', 'actores/Lena Headey.jpg', 1),
(212, 'Bryan Cranston', 'actores/Bryan Cranston.jpg', 1),
(213, 'Aaron Paul', 'actores/Aaron Paul.jpg', 1),
(214, 'Anna Gunn', 'actores/Anna Gunn.jpg', 1),
(215, 'Bob Odenkirk', 'actores/Bob Odenkirk.jpg', 1),
(216, 'Millie Bobby Brown', 'actores/Millie Bobby Brown.jpg', 1),
(217, 'Finn Wolfhard', 'actores/Finn Wolfhard.jpg', 1),
(218, 'Winona Ryder', 'actores/Winona Ryder.jpg', 1),
(219, 'David Harbour', 'actores/David Harbour.jpg', 1),
(220, 'James Gandolfini', 'actores/James Gandolfini.jpg', 1),
(221, 'Edie Falco', 'actores/Edie Falco.jpg', 1),
(222, 'Michael K. Williams', 'actores/Michael K. Williams.jpg', 1),
(223, 'Dominic West', 'actores/Dominic West.jpg', 1),
(224, 'Evan Rachel Wood', 'actores/Evan Rachel Wood.jpg', 1),
(225, 'Thandiwe Newton', 'actores/Thandiwe Newton.jpg', 1),
(226, 'Claire Foy', 'actores/Claire Foy.jpg', 1),
(227, 'Woody Harrelson', 'actores/Woody Harrelson.jpg', 1),
(228, 'Billy Bob Thornton', 'actores/Billy Bob Thornton.jpg', 1),
(229, 'Kieran Culkin', 'actores/Kieran Culkin.jpg', 1),
(230, 'Sarah Snook', 'actores/Sarah Snook.jpg', 1),
(231, 'Pedro Pascal', 'actores/Pedro Pascal.jpg', 1),
(232, 'Steve Carell', 'actores/Steve Carell.jpg', 1),
(233, 'Jenna Fischer', 'actores/Jenna Fischer.jpg', 1),
(234, 'Jennifer Aniston', 'actores/Jennifer Aniston.jpg', 1),
(235, 'Courteney Cox', 'actores/Courteney Cox.jpg', 1),
(236, 'Homer Simpson', 'actores/Homer Simpson.jpg', 1),
(237, 'Marge Simpson', 'actores/Marge Simpson.jpg', 1),
(238, 'Sophie Turner', 'actores/Sophie Turner.jpg', 1),
(239, 'Elisabeth Moss', 'actores/Elisabeth Moss.jpg', 1),
(240, 'Andrew Lincoln', 'actores/Andrew Lincoln.jpg', 1),
(241, 'Norman Reedus', 'actores/Norman Reedus.jpg', 1),
(242, 'Mads Mikkelsen', 'actores/Mads Mikkelsen.jpg', 1),
(243, 'Phoebe Waller-Bridge', 'actores/Phoebe Waller-Bridge.jpg', 1);