INSERT INTO noticias (titulo, contenido, categoria, imagen_principal, alt_imagen_principal, vistas, tiempo_lectura, es_exclusiva, fecha_edicion, fecha_publicacion, creador_id) VALUES
-- Categoría: Cine (6 noticias)
(
    '‘Sinners’ de Ryan Coogler redefine el cine de terror en 2025',
    'En un año lleno de éxitos cinematográficos, *Sinners*, la nueva película de terror dirigida por Ryan Coogler, ha marcado un hito en la industria. Estrenada el 15 de marzo de 2025, la película ha recaudado más de $500 millones en taquilla global en sus primeras dos semanas, convirtiéndose en uno de los mayores éxitos del año. La cinta, que combina elementos de horror sobrenatural con un trasfondo social, ha sido elogiada por su narrativa innovadora y su reparto estelar, encabezado por Michael B. Jordan y Lupita Nyong’o. La trama sigue a un grupo de sobrevivientes en un mundo postapocalíptico donde entidades sobrenaturales acechan a la humanidad, obligándolos a confrontar sus propios demonios internos. Los críticos han destacado la dirección magistral de Coogler, quien utiliza una paleta visual oscura y una banda sonora inquietante para crear una atmósfera envolvente. Los efectos visuales, a cargo de Industrial Light & Magic, han sido descritos como revolucionarios, especialmente en las escenas de confrontación con las entidades. *Sinners* ha generado un intenso debate en redes sociales, con fans creando teorías sobre un posible universo expandido. Disponible en cines y proyectada para streaming en diciembre de 2025.',
    'Cine',
    'noticias/sinners_poster.jpg',
    'Póster oficial de la película Sinners de Ryan Coogler',
    12000,
    8,
    1,
    NOW(),
    NOW(),
    1
),
(
    '‘Eclipse Eternal’ ilumina la ciencia ficción con una épica espacial',
    'Lanzada el 22 de abril de 2025, *Eclipse Eternal*, dirigida por la visionaria Denis Villeneuve, ha redefinido el género de la ciencia ficción con su ambiciosa narrativa intergaláctica. La película, que cuenta con un presupuesto de $300 millones, ha recaudado $650 millones en taquilla global en menos de un mes, consolidándose como un fenómeno cultural. Protagonizada por Timothée Chalamet y Anya Taylor-Joy, la cinta explora la lucha de una civilización humana en un sistema estelar al borde del colapso, enfrentándose a una inteligencia artificial rebelde que amenaza con erradicar la vida orgánica. La dirección de Villeneuve, conocida por su precisión visual, combina paisajes cósmicos generados por CGI con secuencias prácticas que evocan la grandeza de *2001: Una odisea del espacio*. La banda sonora, compuesta por Hans Zimmer, ha sido aclamada por su capacidad para transmitir la vastedad del espacio y la tensión emocional de los personajes. Los efectos especiales, liderados por Weta Digital, han establecido un nuevo estándar en la representación de agujeros negros y batallas espaciales. En redes sociales, los fans han creado memes y teorías sobre el final ambiguo de la película, que deja abierta la posibilidad de una secuela. *Eclipse Eternal* estará disponible en plataformas de streaming a partir de enero de 2026.',
    'Cine',
    'noticias/eclipse_eternal_poster.jpg',
    'Póster oficial de la película Eclipse Eternal de Denis Villeneuve',
    15000,
    9,
    1,
    NOW(),
    NOW(),
    1
),
(
    '‘Sombras de Neón’ lleva el cyberpunk a nuevas alturas en 2025',
    'La directora Chloe Zhao sorprende al mundo con *Sombras de Neón*, una obra maestra del cyberpunk estrenada el 10 de mayo de 2025. Con un elenco liderado por Zendaya y John Boyega, la película ha recaudado $420 millones en taquilla global y ha sido aclamada por su estética retrofuturista y su profunda exploración de la identidad en un mundo dominado por megacorporaciones. La trama sigue a una hacker fugitiva que descubre un complot para controlar la conciencia humana a través de implantes neurales. Zhao combina una dirección íntima con secuencias de acción vertiginosas, utilizando una paleta de colores neón que recuerda a *Blade Runner*. La banda sonora, creada por Daft Punk, ha sido un éxito en plataformas como Spotify, con más de 10 millones de streams en su primera semana. Los efectos visuales, a cargo de Double Negative, destacan por su representación de ciudades futuristas y realidades virtuales. En redes sociales, *Sombras de Neón* ha inspirado fan art y discusiones sobre el impacto de la tecnología en la sociedad. La película estará disponible en streaming en febrero de 2026.',
    'Cine',
    'noticias/sombras_neon_poster.jpg',
    'Póster oficial de la película Sombras de Neón de Chloe Zhao',
    11000,
    7,
    0,
    NOW(),
    NOW(),
    1
),
(
    '‘El Último Refugio’ conmueve con su drama postapocalíptico',
    'Estrenada el 5 de junio de 2025, *El Último Refugio*, dirigida por Alfonso Cuarón, ha capturado los corazones de audiencias globales con su emotiva historia sobre la supervivencia y la esperanza. La película, protagonizada por Diego Luna y Florence Pugh, ha recaudado $380 millones en taquilla y ha sido nominada a múltiples premios por su guion y actuaciones. La trama sigue a un grupo de refugiados que buscan un mítico santuario en un mundo devastado por desastres climáticos. Cuarón utiliza planos secuencia largos y una cinematografía cruda para sumergir al espectador en la desesperación y la resiliencia de los personajes. La banda sonora, compuesta por Max Richter, ha sido descrita como “desgarradora” y ha generado un impacto emocional en los espectadores. Los efectos prácticos, combinados con CGI de Framestore, crean un mundo devastado pero visualmente impactante. En redes sociales, los fans han compartido citas inspiradoras del guion, y la película ha sido trending topic durante semanas. *El Último Refugio* estará disponible en streaming en marzo de 2026.',
    'Cine',
    'noticias/ultimo_refugio_poster.jpg',
    'Póster oficial de la película El Último Refugio de Alfonso Cuarón',
    13000,
    8,
    1,
    NOW(),
    NOW(),
    1
),
(
    '‘Cazadores de Mitos’ revive el cine de aventuras con un giro moderno',
    'Lanzada el 20 de julio de 2025, *Cazadores de Mitos*, dirigida por Greta Gerwig, ha revitalizado el género de aventuras con una mezcla de humor, acción y mitología. Protagonizada por Saoirse Ronan y Chris Hemsworth, la película ha recaudado $510 millones en taquilla global y ha sido elogiada por su guion ingenioso y personajes carismáticos. La trama sigue a un equipo de arqueólogos que descubren un artefacto antiguo que desata fuerzas mitológicas en el mundo moderno. Gerwig combina una dirección vibrante con referencias a clásicos como *Indiana Jones*, mientras aborda temas de diversidad y trabajo en equipo. Los efectos visuales, a cargo de ILM, destacan en las secuencias de acción que involucran criaturas mitológicas. La banda sonora, compuesta por Ludwig Göransson, incorpora instrumentos tradicionales para dar un toque épico. En redes sociales, los fans han creado hashtags como #CazadoresDeMitos y han compartido teorías sobre una posible franquicia. La película estará disponible en streaming en abril de 2026.',
    'Cine',
    'noticias/cazadores_mitos_poster.jpg',
    'Póster oficial de la película Cazadores de Mitos de Greta Gerwig',
    14000,
    7,
    0,
    NOW(),
    NOW(),
    1
),
(
    '‘Horizonte Silencioso’ explora el drama psicológico en el espacio',
    'Estrenada el 15 de agosto de 2025, *Horizonte Silencioso*, dirigida por Christopher Nolan, ha sido aclamada como una de las películas más introspectivas del año. Con un reparto liderado por Cillian Murphy y Jessica Chastain, la cinta ha recaudado $470 millones en taquilla y ha generado debates sobre la salud mental y la soledad. La trama sigue a una tripulación de astronautas atrapada en una estación espacial donde fenómenos inexplicables desafían su percepción de la realidad. Nolan utiliza una narrativa no lineal y una cinematografía claustrofóbica para sumergir al espectador en la psique de los personajes. La banda sonora, compuesta por Hildur Guðnadóttir, utiliza sonidos ambientales para amplificar la tensión. Los efectos visuales, creados por MPC, recrean con precisión entornos espaciales y anomalías gravitacionales. En redes sociales, los fans han analizado el final abierto de la película, generando teorías sobre su significado. *Horizonte Silencioso* estará disponible en streaming en mayo de 2026.',
    'Cine',
    'noticias/horizonte_silencioso_poster.jpg',
    'Póster oficial de la película Horizonte Silencioso de Christopher Nolan',
    12500,
    9,
    1,
    NOW(),
    NOW(),
    1
),
(
    '‘El Eco del Vacío’ redefine el drama distópico en 2025',
    'Estrenada el 10 de marzo de 2025 en la plataforma de streaming Nexus, *El Eco del Vacío* se ha convertido en un fenómeno global, acumulando más de 50 millones de horas vistas en su primera semana. Creada por la showrunner Ava DuVernay, esta serie distópica explora un futuro donde la humanidad vive en bunkers subterráneos tras un colapso ecológico. Protagonizada por Yahya Abdul-Mateen II y Tessa Thompson, la trama sigue a un grupo de rebeldes que descubren secretos sobre el origen del cataclismo. La serie combina un guion emocionalmente profundo con una cinematografía que utiliza tonos fríos para reflejar la desolación del mundo. Los efectos visuales, a cargo de Framestore, han sido elogiados por su representación de paisajes subterráneos y tecnología futurista. La banda sonora, compuesta por Trent Reznor y Atticus Ross, ha generado millones de streams en Spotify. En redes sociales, los fans han creado teorías sobre un posible giro en la segunda temporada, confirmada para 2026. La serie ha recibido elogios por su diversidad en el reparto y su comentario social sobre el cambio climático.',
    'Series',
    'noticias/eco_vacio_poster.jpg',
    'Póster oficial de la serie El Eco del Vacío de Ava DuVernay',
    18000,
    7,
    1,
    NOW(),
    NOW(),
    1
),
(
    '‘Neón Fracturado’ lleva el cyberpunk a la pantalla chica',
    'Lanzada el 25 de abril de 2025 en StreamVerse, *Neón Fracturado* ha capturado la atención de los amantes del cyberpunk con su estética vibrante y narrativa compleja. Creada por los hermanos Russo, la serie sigue a una mercenaria (interpretada por Florence Pugh) que navega una megaciudad controlada por inteligencia artificial. Con 30 millones de horas vistas en su estreno, la serie ha sido renovada para una segunda temporada. La dirección combina acción trepidante con momentos introspectivos, explorando temas de libertad y vigilancia. Los efectos visuales, realizados por Weta Digital, destacan por sus paisajes urbanos iluminados por neón y secuencias de realidad aumentada. La banda sonora, creada por Tame Impala, ha sido un éxito en plataformas musicales. En redes sociales, los hashtags #NeonFracturado y #Cyber2025 han generado miles de publicaciones, con fans discutiendo el cliffhanger del final de temporada. La serie estará disponible en StreamVerse hasta 2027.',
    'Series',
    'noticias/neon_fracturado_poster.jpg',
    'Póster oficial de la serie Neón Fracturado de los hermanos Russo',
    16000,
    6,
    0,
    NOW(),
    NOW(),
    1
),
(
    '‘Sombras de la Corona’ revitaliza el drama histórico',
    'Estrenada el 15 de mayo de 2025 en PrimeStream, *Sombras de la Corona* ha sido aclamada como una de las mejores series históricas del año, con 25 millones de horas vistas en su primera semana. Creada por Peter Morgan, la serie explora intrigas políticas en una corte ficticia del siglo XVIII, protagonizada por Olivia Colman y Regé-Jean Page. La trama mezcla traiciones, romances y luchas de poder, con un guion que equilibra precisión histórica con giros modernos. La producción destaca por sus elaborados vestuarios y escenarios filmados en castillos europeos reales. Los efectos visuales, a cargo de MPC, recrean batallas y eventos históricos con gran detalle. La banda sonora, compuesta por Alexandre Desplat, ha sido nominada a premios por su elegancia. En redes sociales, los fans han comparado la serie con *The Crown* y han creado memes sobre los diálogos ingeniosos. La segunda temporada está programada para 2026.',
    'Series',
    'noticias/sombras_corona_poster.jpg',
    'Póster oficial de la serie Sombras de la Corona de Peter Morgan',
    14000,
    8,
    1,
    NOW(),
    NOW(),
    1
),
(
    '‘Lazos Rotos’ conmueve con su drama familiar sci-fi',
    'Lanzada el 5 de junio de 2025 en HorizonTV, *Lazos Rotos* ha tocado la fibra sensible de las audiencias con su mezcla de ciencia ficción y drama familiar. Creada por Shonda Rhimes, la serie sigue a una familia separada por un experimento temporal que altera sus vidas. Protagonizada por Viola Davis y Daniel Kaluuya, ha acumulado 40 millones de horas vistas en su estreno. La narrativa entrelaza líneas temporales con una dirección visual que utiliza colores cálidos para el pasado y fríos para el futuro. Los efectos visuales, creados por ILM, destacan en las secuencias de viajes temporales. La banda sonora, compuesta por Billie Eilish, ha sido un éxito viral, con su tema principal acumulando millones de reproducciones. En redes sociales, los fans han creado hilos analizando los saltos temporales y teorías sobre el final. La serie ha sido renovada para una segunda temporada en 2026.',
    'Series',
    'noticias/lazos_rotos_poster.jpg',
    'Póster oficial de la serie Lazos Rotos de Shonda Rhimes',
    17000,
    7,
    1,
    NOW(),
    NOW(),
    1
),
(
    '‘Cazadores del Horizonte’ redefine la aventura fantástica',
    'Estrenada el 20 de julio de 2025 en MythicStream, *Cazadores del Horizonte* ha revitalizado el género de fantasía con una épica aventura sobre un grupo de exploradores en un mundo lleno de criaturas míticas. Creada por Neil Gaiman, la serie cuenta con Anya Taylor-Joy y Tom Hiddleston en los papeles principales y ha acumulado 35 millones de horas vistas. La producción destaca por sus efectos visuales de Double Negative, que recrean dragones y paisajes fantásticos con un realismo impresionante. La banda sonora, compuesta por Bear McCreary, incorpora instrumentos medievales para una atmósfera inmersiva. La narrativa combina acción, mitología y dilemas éticos, ganándose elogios de los críticos. En redes sociales, los fans han creado fan art y teorías sobre los orígenes de las criaturas. La segunda temporada está confirmada para 2026.',
    'Series',
    'noticias/cazadores_horizonte_poster.jpg',
    'Póster oficial de la serie Cazadores del Horizonte de Neil Gaiman',
    15500,
    8,
    0,
    NOW(),
    NOW(),
    1
),
(
    '‘Susurros del Más Allá’ combina terror y misterio en 2025',
    'Lanzada el 10 de agosto de 2025 en DarkFlix, *Susurros del Más Allá* ha aterrorizado y fascinado a las audiencias con su mezcla de horror sobrenatural y misterio psicológico. Creada por Mike Flanagan, la serie sigue a un detective (interpretado por Oscar Isaac) que investiga desapariciones vinculadas a una entidad paranormal. Con 45 millones de horas vistas en su estreno, la serie ha sido renovada para una segunda temporada. La dirección utiliza una cinematografía oscura y primeros planos para generar tensión, mientras que los efectos visuales de Framestore recrean apariciones escalofriantes. La banda sonora, compuesta por The Newton Brothers, ha sido elogiada por su atmósfera inquietante. En redes sociales, los fans han compartido teorías sobre la identidad de la entidad y han creado hashtags como #Susurros2025. La serie estará disponible en DarkFlix hasta 2027.',
    'Series',
    'noticias/susurros_mas_alla_poster.jpg',
    'Póster oficial de la serie Susurros del Más Allá de Mike Flanagan',
    19000,
    9,
    1,
    NOW(),
    NOW(),
    1
);